### ISSUE TITLE
event.preventDefault() not working as shown in documentation

### ISSUE THREAD

**Issue by benjaminkalk** [manifestinteractive/jqvmap#171]
I was attempting to disable the clicking as seen in the documentation, but it did not work.  Upon further investigation in jquery.vmap.js I found that the event parameter being used in 'regionClick.jqvmap', is not the same as "regionClickEvent" param in the delegate.  For grins, I passed the regionClickEvent as a fourth parameter to the 'regionClick.jqvmap', and set that fourthParam.preventDefault(), which gave the desired result.

This is the code i changed in jquery.vmap.js delegate to add the fourth param regionClickEvent:
```javascript
jQuery(params.container).trigger('regionClick.jqvmap', [code, mapData.pathes[code].name, regionClickEvent, ]);
```

This is the code setting up the event handler in app code:

onRegionClick: function(event, code, region, realEvent){

          if(inactiveStates.indexOf(code.toUpperCase()) != -1){
            realEvent.preventDefault();
          }

One other note.  It is very easy to cause an error that behaves as if the event.preventDefault worked correctly.  For instance if you were to misspell evnt.preventDefault(), then the region would not become clicked and you can only see the error in the console.

**Comment by manifestinteractive** [comment]
@benjaminkalk it sounds like you found a bug.  Can you submit this as a PR so we can give you credit for the fix?

**Comment by benjaminkalk** [comment]
Submitted the PR just now.

On Tue, Nov 17, 2015 at 4:00 AM, Peter Schmalfeldt <notifications@github.com

**Comment by manifestinteractive** [comment]
This issue should now be resolved.  If it creeps back in, we can reopen it.

**Comment by RongBranovate** [comment]
I'm still not able to disable clicking on countries, used:

```javascript
            onRegionClick: function(event){
                event.preventDefault();
            },
```
But nothing happens...
